### ISSUE TITLE
Discussion: UI tweaks around expansion panels

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosademo-frontend#13]
Overall I think the addition of the expansion panels is great and really cleans up the annotation panel. I freely admit that I am not a great UI designer, but I'd like to start a discussion of some things that could be tweaked with this implementation. @GroovinChip may have some ideas or feedback

_Non-final list_

* Do we need more of a distinction between the transcription and associated expansion panels? 
  * Maybe just an on-hover color change for the clickable labels
* Since different annotations are now encapsulated in expansion panels, I don't think translation or georef annotations need the left indent / left margin anymore
* Georef annotation specifically have extra left margin/padding and left border which can all go away
* Looks like there is a rogue semicolon rendered with the translations

**Comment by GroovinChip** [comment]
Addressing your points in no particular order:
- I think you're right about not needing the left indent for the expansion panels. I will update that. Same for the georef padding.
- I will check out the rogue semicolon and remove it 
- Not really sure what you mean about having more of a distinction between transcription and panels

**Comment by GroovinChip** [comment]
BTW it turns out that the panels themselves have their own padding, it wasn't something we were setting. I'm updating them to ensure the padding is removed.

**Comment by jabrah** [comment]
I was wondering if it would be worth it to show some visual difference on the expansion panels. A light background color or border might be a bit much, I think. Maybe it could use an on-hover color for the expansion panel summary (the clickable part)?

![image](https://user-images.githubusercontent.com/5167587/82071434-1509fb00-96a4-11ea-9243-7ff58a3a98bb.png)

**Comment by GroovinChip** [comment]
All padding issues have been dealt with, rogue semicolon is no longer rendered. Labels and their values now render on the same line for better reading. When expanding a panel, the title and button now highlight in blue. See screenshot:
![chrome_mRmVqYrJ0p](https://user-images.githubusercontent.com/4250470/82093901-02a2b800-96ca-11ea-9336-b2f83b25bc95.png)
