### ISSUE TITLE
Show tags as chips

### ISSUE THREAD

**Issue by GroovinChip** [jhu-digital-manuscripts/rosademo-frontend#18]
Instead of displaying tags as plain text like this:
![chrome_GJykcXFDRO](https://user-images.githubusercontent.com/4250470/83177248-b9506080-a0ec-11ea-936d-2b0fabf1db27.png)
Display a [Material chip](https://material-ui.com/components/chips/) instead, maybe with a 'tag' icon.

**Comment by GroovinChip** [comment]
![chrome_BJYGpsrOho](https://user-images.githubusercontent.com/4250470/83427568-ef4c5800-a3fe-11ea-80d1-d494d7a28ca9.png)

@jabrah thoughts?

**Comment by jabrah** [comment]
I like the look of the 2nd one

**Comment by GroovinChip** [comment]
Awesome
