### ISSUE TITLE
Think about display options for annotation label and annotation comment

### ISSUE THREAD

**Issue by GroovinChip** [jhu-digital-manuscripts/rosademo-frontend#22]
![chrome_MsukEYAQ6o](https://user-images.githubusercontent.com/4250470/83178472-8c04b200-a0ee-11ea-8839-4216c45614e3.png)

This is very busy. Think about how much of this is truly needed and if any of if can be condensed or displayed differently.

**Comment by jabrah** [comment]
This comment is probably also applicable to a few of the other current tickets.

Each annotation body is rendered separately from the others right now and the AnnotationBody component doesn't know anything about its ultimate positioning. Instead, we can expand our changes to the Annotation component, specifically to https://github.com/jhu-digital-manuscripts/rosademo-frontend/blob/master/src/plugins/jh-annotations-panel/components/annotation.js#L51-L63 . Doing so may give us more options for rendering the annotation bodies. For example, we may be able to filter or group annotation bodies from this place.
