### ISSUE TITLE
Annotation count for Homer canvases is broken

### ISSUE THREAD

**Issue by GroovinChip** [jhu-digital-manuscripts/rosademo-frontend#5]
![firefox_ONDj79JCda](https://user-images.githubusercontent.com/4250470/79770817-e8103580-82fb-11ea-883f-e81fdef45bb7.png)

**Comment by jabrah** [comment]
I think this is the same problem we ran into before, the annotation count is using an old selector from base Mirador, which filters annotations by motivation, which our web annotations don't necessarily follow

https://github.com/jhu-digital-manuscripts/rosademo-frontend/blob/master/src/plugins/jh-annotations-panel/container.js#L108

**Comment by GroovinChip** [comment]
It's worth noting that `receiveAnnotation` can take an AnnotationPage, which will probably help with this. See https://github.com/GroovinChip/RoseDemo-FrontEnd/blob/master/src/WebAnnotationsPlugin.js#L53

**Comment by GroovinChip** [comment]
I don't remember how we got around that before, but it looks like the way we process Rosa and Unprocessed annotations is different. For Rosa we call a function to process the items for an AnnotationPage, but for unprocessed we just stuck the `results` in.

https://github.com/jhu-digital-manuscripts/rosademo-frontend/blob/master/src/plugins/jh-annotation-fetch-plugin/webAnnotationUtils.js#L50
